name: "I'd Rather Be Writing"
description: Technical writing blog focusing on the latest trends, news, and other topics in the field of technical communication.
host: 127.0.0.1
port: 4029
feedback_email: tomjohnson1492@gmail.com
sidebar_accordion: true
disqus_shortname: idratherbewriting
google_analytics: UA-408430-5
markdown: redcarpet
show_audience_label: true
output: web
paginate: 15
timezone: America/Los_Angeles
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

gems: [jekyll-sitemap, jekyll-mentions, jekyll-redirect-from, jekyll-feed, jekyll-paginate]

#url: "http://tomjohnson1492.github.io"
url: http://idratherbewriting.com
exclude:
  - _drafts
  - .idea
  - _site

# this enables collections
collections:
  restapicourse:
    output: true
  publishingapidocs:
    output: true
  voiceovertechniques:
    output: true

# these are defaults that get applied to each page or post's frontmatter. leave as is.
permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips_demo"
    values:
      layout: "page"
      search: true
  -
    scope:
      path: ""
      type: "restapicourse"
    values:
      layout: "page_restapicourse"
      comments: true
      search: true

  -
    scope:
      path: ""
      type: "revisioncontrol"
    values:
      layout: "page"
      comments: true
      search: true

sass:
    sass_dir: _sass
baseurl:  /idrbr/
